_format_version: "3.0"
_transform: true

consumers:
- username: app-consumer
  jwt_secrets:
  - key: kid  #tên key quan trọng phải trùng với kid khi người đăng nhập tạo token
    secret: phihung812 #tên key ở trong authModule secret key
    algorithm: HS256

services:
- name: user-service
  url: http://host.docker.internal:3000
  routes:
    - name: user-post-route
      paths:
        - /users
      methods:
        - POST
      strip_path: false

    - name: user-route
      paths:
        - /users
        - /users/upload-avatar
      methods:
        - GET
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
      strip_path: false
      plugins:
        - name: jwt
          config:
            secret_is_base64: false
            key_claim_name: kid
            claims_to_verify:
            - exp
          
- name: post-service
  protocol: http
  host: host.docker.internal
  port: 3002
  path: /
  routes:
  - name: add-post-route
    paths:
    - /posts
    - /posts/list-post
    - /posts-user-profile/
    strip_path: false
    plugins:
    - name: jwt
      config:
        secret_is_base64: false
        key_claim_name: kid
        claims_to_verify:
        - exp

- name: social-graph-service
  protocol: http
  host: host.docker.internal
  port: 3004
  path: /
  routes:
  - name: follow-route
    paths:
    - /graph/follow
    - /graph/unfollow
    strip_path: false
    plugins:
    - name: jwt
      config:
        secret_is_base64: false
        key_claim_name: kid
        claims_to_verify:
        - exp

- name: interaction-service
  protocol: http
  host: host.docker.internal
  port: 3005
  path: /
  routes:
  - name: interaction-route
    paths:
    - /interaction/like
    - /interaction/comment
    - /interaction/comment/replies
    - /interaction/saved-post
    strip_path: false
    plugins:
    - name: jwt
      config:
        secret_is_base64: false
        key_claim_name: kid
        claims_to_verify:
        - exp

- name: notification-service
  protocol: http
  host: host.docker.internal
  port: 3050
  path: /
  routes:
  - name: notification-route
    paths:
    - /notification
    strip_path: false
    plugins:
    - name: jwt
      config:
        secret_is_base64: false
        key_claim_name: kid
        claims_to_verify:
        - exp

- name: message-service
  protocol: http
  host: host.docker.internal
  port: 3070
  path: /
  routes:
  - name: message-route
    paths:
    - /message
    - /conversation
    strip_path: false
    plugins:
    - name: jwt
      config:
        secret_is_base64: false
        key_claim_name: kid
        claims_to_verify:
        - exp

- name: search-global-service
  protocol: http
  host: host.docker.internal
  port: 3003
  path: /
  routes:
  - name: search-global-route
    paths:
    - /api/search
    strip_path: false
    plugins:
    - name: jwt
      config:
        secret_is_base64: false
        key_claim_name: kid
        claims_to_verify:
        - exp

- name: auth-service
  protocol: http
  host: host.docker.internal
  port: 3001
  path: /
  routes:
  - name: auth-login-route
    paths:
    - /auth/login
    strip_path: false

  - name: auth-logout-route
    paths:
    - /auth/logout
    strip_path: false
   

  - name: auth-refresh
    paths:
    - /auth/refresh
    strip_path: false


plugins:
- name: cors
  config:
    origins:
    - http://localhost:5173  #cho phép api này gửi req đến kong
    methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    - PATCH
    headers:
    - Authorization
    - Content-Type
    credentials: true

- name: rate-limiting
  config:
    minute: 100
    hour: 1000
    policy: local